### ISSUE TITLE
IllegalAccessError for net.bytebuddy.dynamic.Nexus.NO_QUEUE

### ISSUE THREAD

**Issue by ahatzz11** [nccgroup/log4j-jndi-be-gone#6]
This is a cross-reference post to an issue I made in bytebuddy: https://github.com/raphw/byte-buddy/issues/1179

We're trying to run this in our environment and having some issues. I'm not an expert in javaagents/bytebuddy so I'm hoping to get some help here, or maybe suggest some improvements to this repo.

Is this agent being built with the latest version of bytebuddy? I see a min version is being defined here, but unsure how that plays into it all: https://github.com/nccgroup/log4j-jndi-be-gone/blob/main/build.gradle#L18

**Something that was suggested in that other issue is shading ByteBuddy so there wouldn't be a potential conflict with something else on the classpath. Is this something that would be doable?**

---

When running our application with the following `JAVA_OPTS`:

```
-javaagent:/opt/datadog/dd-java-agent.jar -javaagent:/opt/log4j-jndi-be-gone/log4j-jndi-be-gone.jar '
```

We get the following in some of our applications:

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:500)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:512)
Caused by: java.lang.IllegalAccessError: tried to access field net.bytebuddy.dynamic.Nexus.NO_QUEUE from class net.bytebuddy.dynamic.NexusAccessor
	at net.bytebuddy.dynamic.NexusAccessor.<init>(NexusAccessor.java:68)
	at net.bytebuddy.agent.builder.AgentBuilder$InitializationStrategy$SelfInjection$Split.<init>(AgentBuilder.java:3169)
	at net.bytebuddy.agent.builder.AgentBuilder$Default.<init>(AgentBuilder.java:8397)
	at net.bytebuddy.agent.builder.AgentBuilder$Default.<init>(AgentBuilder.java:8385)
	at trust.nccgroup.jndibegone.hooks.JndiLookup__lookup.hook(JndiLookup__lookup.java:51)
	at trust.nccgroup.jndibegone.Agent.load(Agent.java:26)
	at trust.nccgroup.jndibegone.PreMain.premain(PreMain.java:27)
	... 6 more
FATAL ERROR in native method: processing of -javaagent failed
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f6ab2ef0324, pid=1, tid=11
#
# JRE version: OpenJDK Runtime Environment (9.0+12) (build 9.0.4+12-Debian-4)
# Java VM: OpenJDK 64-Bit Server VM (9.0.4+12-Debian-4, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libc.so.6+0x36324]  abort+0x244
```

Any help would be appreciated!

**Comment by ChaosData** [comment]
Can you confirm if this is still an issue with the v1.1.0 standalone JAR from releases?

**Comment by ChaosData** [comment]
@ahatzz11?

**Comment by ahatzz11** [comment]
Hey @ChaosData, we haven't done any wide-scale testing yet, but in an application we know broke before because of an old version of bytebuddy on the classpath it did successfully work, so we are 1/1 so far. I'm hoping to work with our devops team to do more extensive testing rollouts next week, and can let you know.

**Comment by ahatzz11** [comment]
@ChaosData We deployed `v1.1.0` to our test environment today, roughly ~1000 pods, and everything went great with the shading. Thanks for the help!
